# Generated by Django 5.2.1 on 2025-06-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('bills', 'Bills'), ('education', 'Education'), ('clothes', 'Clothes'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('othealthher', 'Health'), ('other', 'Other')], max_length=100),
        ),
    ]
