# Generated by Django 5.2.1 on 2025-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_amount_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('bills', 'Bills'), ('education', 'Education'), ('clothes', 'Clothes'), ('electronics', 'Electronics'), ('entertainment', 'Entertainment'), ('health', 'Health'), ('other', 'Other')], max_length=100),
        ),
    ]
